### ISSUE TITLE
dev branch: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jarbuz** [DHowett/spectre#11]
compiled from source. change was made in main.go, auth.go and permissions.go:

import

"./account" was changed to "github.com/ghostbin/account" as it would not build with other path specified.

Compiled perfectly. Run on a x64 ubuntu 14.04:

~/go/bin$ ./ghostbin 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x40170b]

Anyway I can provide you more information?

**Comment by jimmybrancaccio** [comment]
I was also getting this error. I basically used the same method on Ubuntu 14.04 x86_64. I'd love to get this up and running. :smile:

**Comment by DHowett** [comment]
We may have fixed this in ee80044161b9f4cf09f3a3a56fe11c3541846ee9 -- delete all your autogenerated cookie keys and try again.
I haven't seen this particular issue, unfortunately.

**Comment by jimmybrancaccio** [comment]
Hey @DHowett! Thanks for the update. I tried doing a completely fresh install but I am still getting the same error.

``` bash
ghostbin@paste:~/go/bin$ ./ghostbin
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x40170b]

goroutine 1 [running]:
runtime.panic(0x78bc40, 0xc5e168)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.(*assetFilesystem).recursivelyPopulateMap(0xc21008f200, 0xc210106840, 0x7f5d80, 0x1)
	/home/ghostbin/go/src/github.com/ghostbin/assets.go:86 +0x6b
main.(*assetFilesystem).Populate(0xc21008f200)
	/home/ghostbin/go/src/github.com/ghostbin/assets.go:80 +0x60
main.InitAssets()
	/home/ghostbin/go/src/github.com/ghostbin/assets.go:105 +0x2a
main.ReloadAll()
	/home/ghostbin/go/src/github.com/ghostbin/util.go:139 +0x5e
main.main()
	/home/ghostbin/go/src/github.com/ghostbin/main.go:732 +0x29

goroutine 3 [syscall]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 4 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xc66380)
	/home/ghostbin/go/src/github.com/golang/glog/glog.go:879 +0x50
created by github.com/golang/glog.init·1
	/home/ghostbin/go/src/github.com/golang/glog/glog.go:410 +0x276

goroutine 5 [syscall]:
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1394

goroutine 7 [select]:
github.com/DHowett/gotimeout.(*Expirator).run(0xc21001ef50)
	/home/ghostbin/go/src/github.com/DHowett/gotimeout/expirator.go:160 +0x336
created by github.com/DHowett/gotimeout.NewExpirator
	/home/ghostbin/go/src/github.com/DHowett/gotimeout/expirator.go:59 +0xce

goroutine 8 [select]:
github.com/DHowett/gotimeout.(*Expirator).run(0xc2100f9000)
	/home/ghostbin/go/src/github.com/DHowett/gotimeout/expirator.go:160 +0x336
created by github.com/DHowett/gotimeout.NewExpirator
	/home/ghostbin/go/src/github.com/DHowett/gotimeout/expirator.go:59 +0xce

goroutine 11 [runnable]:
main.func·041()
	/home/ghostbin/go/src/github.com/ghostbin/util.go:195
created by main.init·9
	/home/ghostbin/go/src/github.com/ghostbin/util.go:200 +0x1d2
```

I haven't done a whole lot with Go so I am not sure if I am setting this up completely correctly. I have created a new user 'ghostbin' and stored all my stuff within it's home folder:

/home/ghostbin/go/src/github.com/ghostbin

I still had an issue with the account stuff, I had to manually create the account folder and account.go file in:

/home/ghostbin/go/src/github.com/DHowett/ghostbin

**Comment by DHowett** [comment]
Aha! It looks like you're running ghostbin outside its source directory.

It's not particularly suited to that, unfortunately. It's not a very go-gettable citizen. It looks for its templates, assets, language config, etc., etc. in the directory from which it was started.

The account import should be fixed by now, and all development has switched to `master`.

**Comment by jimmybrancaccio** [comment]
@DHowett Ah hah! Ok, so I rebuilt it again, ran ./ghostbin from it's original directory:

ghostbin@paste:~/go/src/github.com/ghostbin$ ./ghostbin -addr="127.0.0.1:8619" -root="/home/ghostbin/storage" -log_dir="/home/ghostbin/logs"

Now it seems happier, but it looks like Pygments may be having an issue. I installed those:

`# apt-get install python-pygments`

Now I see this in the logs when trying to view a paste:

``` bash
ghostbin@paste:~/go/src/github.com/ghostbin$ ./ghostbin -addr="127.0.0.1:8619" -root="/home/ghostbin/storage" -log_dir="/home/ghostbin/logs"
E0211 17:20:19.752638    5585 main.go:753] Expirator Error: open /home/ghostbin/storage/expiry.gob: no such file or directory
E0211 17:20:21.271285    5585 main.go:554] Render for j2df8 failed: (exec: "./bin/pygments/pygmentize": stat ./bin/pygments/pygmentize: no such file or directory) output: 
```

``` bash
ghostbin@paste:~/go/src/github.com/ghostbin$ whereis pygmentize
pygmentize: /usr/bin/pygmentize /usr/bin/X11/pygmentize /usr/share/man/man1/pygmentize.1.gz
```

Example: http://paste.linuxbox.ninja/paste/j2df8

**Comment by Hekter** [comment]
Gah, you beat me to it--DHowett and I were just talking about how to respond to this and this is the correct solution. It's a bit messy and something we could probably work on, obviously, but I'm glad you got it working!

**Comment by DHowett** [comment]
Closing because:
0. @jimmybrancaccio chose the "right" solution (perhaps not the best solution overall, but **the best solution Ghostbin could handle**)
1. this seems to be resolved
2. `master` is now a full rewrite, and it retains none of the hatred for the world its predecessor displayed
