### ISSUE TITLE
[Suggestion] Update Ghostbin

### ISSUE THREAD

**Issue by OhCreative** [DHowett/spectre#36]
These files have become very outdated and it is horrible to try and install a ghostbin server, so can you please update the code to become recent :)

**Comment by alucard0134** [comment]
Pull Request #37 makes it installable

**Comment by DHowett** [comment]
Hi there. Please try out the `v1-stable` branch. `master` is being used for what is slowly becoming a full rewrite.

**Comment by alucard0134** [comment]
did someone say rewrite i’m hyped
