### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by lesderid** [DHowett/spectre#38]
This project currently has no license. That makes it proprietary software by default.

The [package.json](https://github.com/DHowett/ghostbin/blob/0376df8b7bc997e6162279f705c51c8cd4c88f0e/package.json#L14) says `GPL`, but that doesn't mean anything. You have to specify a version of the GNU GPL and distribute a copy of the full license with the project.

**Comment by DHowett** [comment]
Good catch. It looks like I failed to actually properly _license_ the project I called open-source.

**Comment by DHowett** [comment]
(I am debating the appropriate strategy here: I'm intending on explicitly licensing the code under MIT, but the branding under some CC derivative.)

**Comment by lesderid** [comment]
What do you mean by branding? Just the logo, or also things like the 
CSS and the about page text?

If the former, you can just add a notice that says something like 
"Ghostbin's logo can be used under the terms of the \<insert license\>.".

If you also want to use a different license for other stuff, it might 
be harder. I think usually something like "Ghostbin is released under 
the \<insert first license\>, except the following files: \<insert files\>. 
These files can be used under the terms of the \<insert second 
license\>." is good enough.

Note that since Ghostin isn't trademarked (afaik), there's little you 
can do about someone using the name 'Ghostbin' for a derivative project.


(IANAL though)

**Comment by neverpanic** [comment]
What's the progress on this? I'm looking for a pastebin service to run for MacPorts, and this looks like a good candidate, but the missing license is a blocker for me :/

**Comment by DHowett** [comment]
Thanks for the interest in Ghostbin. Right now we're not in any state to be used as anyone's pastebin, since I decided it'd be a good idea to rewrite the world.

Moving forward, I'll license the core under MIT and the branding under nothing-because-it-will-live-in-a-separate-repository.
