### ISSUE TITLE
Raw view feature?

### ISSUE THREAD

**Issue by Xibster** [DHowett/spectre#41]
I can't seem to find the 'Raw view' button.
Even the url 'ghostbin.com/paste/XXXXX/raw' doesn't work.

**Comment by Hekter** [comment]
Hi Xibster,

This feature has been disabled on the main site, though still remains active in the code here.

**Comment by Xibster** [comment]
Why was it disabled?

**Comment by Hekter** [comment]
Namely because of abuse. People were using /raw to host scripts that would be called on compromised pageloads, thus delivering unsavory payloads and DDOSing Ghostbin.

**Comment by P4risAndStuff** [comment]
Yup. https://github.com/DHowett/ghostbin/issues/64

**Comment by DHowett** [comment]
This is back, somewhat. I forgot to continue removing it when I moved to automatic CI deployment.
