### ISSUE TITLE
Lost pastes shared with a friend, we still have the cookies, pastes are still up, but we have no permissions to edit them.

### ISSUE THREAD

**Issue by celphtilted** [DHowett/spectre#62]
Also I have seen topics for grey window in login screen, and why they do not work. I would love to hear any response on that, because I am trying to log in for the past months, but it never works, this is somewhat an important feature for some.

**Comment by DHowett** [comment]
This might be caused by #67. You probably still have your session cookie (since it's set to expire in a year), but the server is rejecting it after 30 days. There'll be a fix inbound soon.

**Comment by DHowett** [comment]
@cephtilted Ghostbin v1 is in maintenance mode for now; however, I've deployed a patch for this issue.

If you still have access to your session cookie, can you see whether your pastes came back? I'm really sorry for the inconvenience. This could also have led to a login/account creation failure.

**Comment by DHowett** [comment]
(I've been focusing most of my effort lately on the spectre/ghostbin-v2 split, and since it always feels like it's "right around the corner" i've been deferring maintenance on v1.)

**Comment by celphtilted** [comment]
@DHowett Got the cookies, still cannot see my pastes.

**Comment by DHowett** [comment]
Argh.

Can you email your cookie content to secure-gb@relay.howett.net?
If you managed to make an account, send along its name as well and I'll
merge the old busted session into it.
-- 
-- Dustin L. Howett

**Comment by DHowett** [comment]
Closing due to lack of response. If you have more to add, please feel free to reopen!
