### ISSUE TITLE
After saving a paste a few times, ghostbin goes full blank white page and it does not let me edit the paste any further until I have a new IP.

### ISSUE THREAD

**Issue by celphtilted** [DHowett/spectre#63]
I have noticed that whenever I update a paste on Ghostbin, after multiple saves the website loads a white blank page and it stays like that until getting a new IP. This happens when editing any paste, my friends have the same issue, it is crazy annoying and it completely shut downs my usage of GB until I get a new IP.

I use it with friends for school, we sometimes edit it multiple times and we always get "locked out", like I said, this happens with any paste, if I create a new one right now, and edit it 5 times in 15 minutes, the whole website will be blocked from using until I get a new IP address.

Please let me know for any solution.

**Comment by DHowett** [comment]
This is due to the per-IP throttling being a little too harsh :frowning: sorry

I'll loosen the limits.

**Comment by celphtilted** [comment]
It's crazy harsh. I could not open my pastes for over 24 hours, and it goes blank after literally 5 times, this limit needs to be increased dozens of times. And I really don't like how you don't get any answer to why the page is now suddenly blank for the next decennia. Really, a literal shadow ban.

I understand that there are alternatives, but I love GBin, and its unusable for basic stuff because of this problem. If not many people complain about this, than not many are coming to face this problem, meaning that an increase would only be a positive thing.

**Comment by Hekter** [comment]
I keep a running total on how many times I get IP-banned, it's currently at 6 ;)

**Comment by DHowett** [comment]
I've raised the limit from 7 pates per 15 seconds to 30 pastes per 15 seconds. This should still catch the most egregious offenders but not interfere with normal use.

(If you're accessing more than two pastes per second, _please contact me_ :P)

**Comment by Zchap1** [comment]
rip someone sent me a ghostbin link and now I can't access it.
