### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by amenolo** [DHowett/spectre#74]
My case scenario:

Ubuntu server 16.04 properly installed & updated from scratch
Go 1.8.3 & Mercurial properly installed
GOPATH exported to /opt/go

First attempt, Wiki-style:

_cd /opt/go
git clone https://github.com/DHowett/spectre.git
cd spectre
go get_

results in:
**_go install: no install location for directory /home/user/dir/spectre outside GOPATH_**

Second attempt, slightly different:

_cd /opt/go
rm -r spectre
go get github.com/DHowett/spectre_

results in:
**_package github.com/DHowett/spectre: code in directory /opt/go/src/github.com/DHowett/spectre expects import "howett.net/spectre"_**

At this point if I launch _go build_ under /opt/go/src/github.com/DHowett/spectre, file

_/opt/go/pkg/linux_amd64/github.com/DHowett/spectre.a_

is created, so lonely that seems pretty useless to me.
And I'm stuck anyway...

I'm kind of Go-noob (you don't say!), what am I missing here...? :-(

Thanks in advance!

**Comment by Makeshift** [comment]
I'm having this exact issue and I have literally no idea how to fix it. Did you ever get anywhere?

**Comment by schroding3rscat** [comment]
Same issue here with 
> expects import "howett.net/spectre"
Cannot go get the package and build it.

**Comment by DHowett** [comment]
Hi there. Please try out the `v1-stable` branch. `master` is being used for what is slowly becoming a full rewrite.

Sorry for the debris.
