### ISSUE TITLE
Is ghostbin.com down?

### ISSUE THREAD

**Issue by privacytoolsIO** [DHowett/spectre#75]
http://downforeveryoneorjustme.com/ghostbin.com

**Comment by stnby** [comment]
lol I got banned too for trying to use https://ghostbin.com/paste/*/raw

**Comment by Qsaws** [comment]
I can't access ghostbin anymore for some reason, seems to be up for everyone else. I just get a "ghostbin.com took too long to respond"

**Comment by DHowett** [comment]
Firewalling restrictions have been slackened.
