### ISSUE TITLE
can't seem to build due to missing 'ghostbin' dep

### ISSUE THREAD

**Issue by jamesbeedy** [DHowett/spectre#76]
Hello,

Trying to build this project and I can't find the 'ghostbin' dep. Can you help me?

thanks

**Comment by DHowett** [comment]
Hi there. Please try out the `v1-stable` branch. `master` is being used for what is slowly becoming a full rewrite.

**Comment by Makeshift** [comment]
@DHowett Even on the v1-stable branch, Go complains about missing Ghostbin dependencies:

```
package github.com/DHowett/ghostbin/account: cannot find package "github.com/DHowett/ghostbin/account" in any of:
        /usr/lib/go-1.9/src/github.com/DHowett/ghostbin/account (from $GOROOT)
        /home/ubuntu/go/src/github.com/DHowett/ghostbin/account (from $GOPATH)

```

**Comment by mkatychev** [comment]
@Makeshift after spending two hours deciphering the wiki, this is the only thing that worked for me.

Why is the complete rewrite the master branch (this should definitely be in a dev branch), why not just fork a brand new repo and keep the ghostbin one intact? so many counter-intuitive idiosyncrasies...

**Comment by Makeshift** [comment]
@mkatychev Glad it could help someone! I'm still running that same binary :P

**Comment by mkatychev** [comment]
@Makeshift did you manage to find out where to store the languages.yml? should it say in the source folder or is a copy needed in the same path as the binary?

**Comment by Makeshift** [comment]
@mkatychev I put it in the spectre folder and I also run the binary in there.

**Comment by DHowett** [comment]
For what it's worth, there's a bit of a trial-by-fire build script [in the CI configuration](https://gitlab.howett.net/Ghostbin/spectre/blob/v1-stable/.gitlab-ci.yml). Everything that's supposed to be packaged with the _binary_ (or available in your working directory when you run it) is copied in [here](https://gitlab.howett.net/Ghostbin/spectre/blob/v1-stable/.gitlab-ci.yml#L35).

**Comment by DHowett** [comment]
> @mkatychev: "so many counter-intuitive idiosyncrasies"

Oh, absolutely. That's why it's been a pain establishing CI, a pain explaining to people how to run it, a pain actually running it, and a pain doing [pretty much anything else you can imagine]. Committing new work on `master` and parking old work on a servicing branch, however, is too mundane to be one of those idiosyncrasies.

**Comment by mkatychev** [comment]
@DHowett thanks for the tip, I will take a look in the CI
