### ISSUE TITLE
Run over SSL/TLS (https)

### ISSUE THREAD

**Issue by m0m0g33k** [DHowett/spectre#82]
I am running ghostbin perfectly well, but I cannot find how to run in https.

Is there any option to run that from command line? 

t´nX

**Comment by biazzotto** [comment]
I think you could use NGINX to proxy the requests, as you can see here:
[Hosting Your Own Ghostbin](https://jimmyb.ninja/post/1423696494)

**Comment by m0m0g33k** [comment]
t´nX biazzotto!,
