### ISSUE TITLE
CloudFlare

### ISSUE THREAD

**Issue by ObserverOfTime** [DHowett/spectre#86]
Is the CloudFlare protection a permanent change? It's making using the API much harder.

**Comment by DHowett** [comment]
Email me. Let’s chat about the Ghostbin API.

**Comment by bionichuman** [comment]
@ObserverOfTime Its easy to host your own GhostBin. Then you can use anyway you want.

**Comment by DHowett** [comment]
@bionichuman you've said it was easy, but admittedly it _did_ require you asking a hundred questions over the course of two weeks 😄

**Comment by bionichuman** [comment]
Yes but I got everything working now! SSL too! Easy once you understand it... 😄
